[package]
name = "rust-firework-gui-app"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
log = { workspace = true }
open = "5.3.2"
rfd = { workspace = true }
rust-firework-core = { path = "../core" }

slint = { version = "1.14.1" }

[build-dependencies]

slint-build = "1.14.1"
