[package]
name = "tg-cli-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
clap = { version = "4.5.45", features = ["derive"] }

tg-core.path = "../core"
