[package]
name = "rust-firework-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
colored = { version = "3.0.0" }
directories = "6.0.0"
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[build-dependencies]
