import { VerticalBox, AboutSlint, Palette } from "std-widgets.slint";
import { HyperlinkText } from "widgets/hyperlink.slint";

component HorizontalLine inherits HorizontalLayout {
    alignment: center;
    padding-top: 10px;
    padding-bottom: 10px;
    Rectangle {
        height: 2px;
        width: 300px;
        background: Palette.accent-background;
    }
}

export component AboutWindowContent inherits Rectangle {
    in property <string> version: "x.x.x";
    background: Palette.background;
    width: 435px;
    height: 300px;
    border-radius: 6px;
    border-width: 1px;
    border-color: black;
    TouchArea { }

    Image {
        source: @image-url("./assets/apollo_by_maudoggo.png");
        width: 120px;
        x: 325px;
        y: 187px;
    }

    VerticalBox {
        alignment: center;
        Text {
            horizontal-alignment: center;
            font-size: 22px;
            text: "Project TodoGraph";
        }

        Text {
            horizontal-alignment: center;
            text: "An experimental planning tool";
        }

        HorizontalLine { }

        HorizontalLayout {
            alignment: center;
            Text {
                text: "Made with lots of distraction by ";
            }

            HyperlinkText {
                text: "ApolloRoboto";
                path: "https://github.com/Apollo-Roboto";
            }
        }

        Text {
            horizontal-alignment: center;
            text: "Version: " + root.version;
        }

        HorizontalLine { }

        AboutSlint {
            height: 105px;
        }
    }
}
