import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

enum MindTaskState {
    Todo,
    Doing,
    Done,
}

struct MindTask {
    id: int,
    title: string,
    state: MindTaskState,
    x: length,
    y: length,
    completion: float,
}

struct MindEdge {
    from_x: length,
    from_y: length,
    to_x: length,
    to_y: length,
}

component Bubble inherits Rectangle {
    in property <string> text <=> _text.text;
    in property <length> horizontal_padding: 35px;
    in property <length> vertical_padding: 20px;
    height: _text.height + vertical_padding;
    width: _text.width + horizontal_padding;
    border-width: 1px;
    border-color: black;
    border-radius: 16px;
    background: #333333;
    _text := Text { }
}

component DragableRectangle inherits Rectangle {
    callback moved();
    TouchArea {
        moved => {
            root.x = self.mouse-x - self.pressed-x + root.x;
            root.y = self.mouse-y - self.pressed-y + root.y;
        }
    }

    background: #ff000055;
    @children
}

component TaskBubble {
    in property <MindTask> task;
    in property <bool> extra_info: true;
    in property <brush> default_color: #333333;
    in property <brush> todo_color: #333333;
    in property <brush> doing_color: #2c1c74;
    in property <brush> done_color: #11572e;
    callback delete_clicked();
    callback state_change_clicked(state: MindTaskState);
    callback moved_to(x: length, y: length);
    DragableRectangle {
        moved => {
            // TODO: this position isn't right
            root.moved_to(self.x, self.y);
        }
        VerticalLayout {
            HorizontalLayout {
                TouchArea {
                    width: 16px;
                    height: 16px;
                    Rectangle {
                        background: todo_color;
                    }

                    clicked => {
                        debug("State todo task " + task.id + " clicked");
                        root.state_change_clicked(MindTaskState.Todo);
                    }
                }

                TouchArea {
                    width: 16px;
                    height: 16px;
                    Rectangle {
                        background: doing_color;
                    }

                    clicked => {
                        debug("State doing task " + task.id + " clicked");
                        root.state_change_clicked(MindTaskState.Doing);
                    }
                }

                TouchArea {
                    width: 16px;
                    height: 16px;
                    Rectangle {
                        background: done_color;
                    }

                    clicked => {
                        debug("State done task " + task.id + " clicked");
                        root.state_change_clicked(MindTaskState.Done);
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                TouchArea {
                    width: 16px;
                    height: 16px;
                    Rectangle {
                        background: red;
                    }

                    clicked => {
                        debug("Delete task " + task.id + " clicked");
                        root.delete_clicked();
                    }
                }
            }

            Bubble {
                text: task.title;
                background: task.state == MindTaskState.Todo ? todo_color //
                  : task.state == MindTaskState.Doing ? doing_color //
                  : task.state == MindTaskState.Done ? done_color // 
                  : default_color;
            }

            if extra_info:
            HorizontalLayout {
                Text {
                    font-family: "Consolas";
                    text: Math.round(task.completion * 100) + "%";
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                Text {
                    font-family: "Consolas";
                    text: task.id;
                }
            }
        }
    }
}

component PanBox inherits Rectangle {
    // background: #ffffff11;
    clip: true;
    out property <length> center_x: move_me.width / 2;
    out property <length> center_y: move_me.height / 2;
    in property <bool> show_center: true;
    in property <bool> show_position: true;
    public function move_view_to(x: length, y: length) {
        move_me.x = root.width / 2 - x;
        move_me.y = root.height / 2 - y;
    }

    // movable rectangle containing the childrens
    move_me := Rectangle {
        width: 1000px;
        height: 1000px;
        Image {
            source: @image-url("./assets/point_tile_c_150x150.png");
            vertical-tiling: ImageTiling.repeat;
            horizontal-tiling: ImageTiling.repeat;
            width: parent.width;
            height: parent.height;
            opacity: 5%;
        }

        TouchArea {
            moved => {
                move_me.x = self.mouse-x - self.pressed-x + move_me.x;
                move_me.y = self.mouse-y - self.pressed-y + move_me.y;
            }
        }

        @children
        if show_center:
        Rectangle {
            background: red;
            width: 50px;
            height: 2px;
        }
        if show_center:
        Rectangle {
            background: red;
            width: 2px;
            height: 50px;
        }
    }
    
    // overlay
    Rectangle {
        VerticalBox {
            alignment: end;
            if show_position:
            Text {
                opacity: 50%;
                // TODO: This isn't the correct coordinate, I expect the center of the view to line up
                text: "(" + (move_me.x) / 1px + ", " + (move_me.y) / 1px + ")";
            }
        }
    }
}

component Edge inherits Rectangle {
    in property <length> stroke_width <=> p.stroke-width;
    in property <brush> stroke <=> p.stroke;
    in property <length> from_x;
    in property <length> from_y;
    in property <length> to_x;
    in property <length> to_y;
    p := Path {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        viewbox-x: parent.x / 1px;
        viewbox-y: parent.y / 1px;
        viewbox-width: parent.width / 1px;
        viewbox-height: parent.height / 1px;
        stroke: red;
        stroke-width: 3px;
        MoveTo {
            x: (from_x + (p.width / 2)) / 1px;
            y: (from_y + (p.height / 2)) / 1px;
        }

        LineTo {
            x: (to_x + (p.width / 2)) / 1px;
            y: (to_y + (p.height / 2)) / 1px;
        }
    }
}

enum TaskLoadingState {
    None, Loading, Error,
}
enum TaskSavingState {
    None, Saving, Error,
}

export component AppWindow inherits Window {
    in property <[MindTask]> tasks;
    in property <[MindEdge]> edges;
    in property <TaskLoadingState> task_loading_state: TaskLoadingState.None;
    in property <string> task_loading_error_message;
    in property <TaskSavingState> task_saving_state: TaskSavingState.None;
    in property <string> task_saving_error_message;
    callback load(path: string);
    callback save(path: string);
    callback add_task(title: string, x: length, y: length);
    callback delete_task(id: int);
    callback change_state(id: int, state: MindTaskState);
    callback task_moved(id: int, x: length, y: length);
    VerticalBox {
        HorizontalLayout {
            alignment: center;
            pan_box := PanBox {
                width: 600px;
                height: 600px;
                border-color: black;
                border-width: 1px;
                border-radius: 6px;

                // // temp line
                // Path {
                //     width: parent.width;
                //     height: parent.width;
                //     x: parent.x;
                //     y: parent.y;
                //     viewbox-x: parent.x / 1px;
                //     viewbox-y: parent.y / 1px;
                //     viewbox-width: parent.width / 1px;
                //     viewbox-height: parent.height / 1px;
                //     stroke: #ff0000aa;
                //     stroke-width: 3px;
                //     private property <length> from_x: bubble_a.x + bubble_a.width / 2;
                //     private property <length> from_y: bubble_a.y + bubble_a.height / 2;
                //     private property <length> to_x: bubble_b.x + bubble_b.width / 2;
                //     private property <length> to_y: bubble_b.y + bubble_b.height / 2;
                //     MoveTo {
                //         x: from_x / 1px;
                //         y: from_y / 1px;
                //     }

                //     LineTo {
                //         x: to_x / 1px;
                //         y: to_y / 1px;
                //     }
                // }

                // // temp bubble
                // bubble_a := Bubble {
                //     x: pan_box.center_x;
                //     y: pan_box.center_y;
                //     text: "Do Thing";
                // }


                // temp edges
                for edge in [
                    [-100px, 0px, 100px, 100px],
                    [50px, 25px, 100px, 25px],
                    [100px, 100px, 200px, 200px],
                    [100px, 100px, 200px, 100px],
                    //
                    [0px, 0px, -30px, 0px],
                    [0px, 0px, -30px, 30px], // doesn't show
                    [0px, 0px, -30px, -30px],
                    [0px, 0px, 0px, 30px],
                    [0px, 0px, 0px, -30px],
                    [0px, 0px, 30px, -30px], // doesn't show
                    [0px, 0px, 30px, 0px],
                    [0px, 0px, 30px, 30px],
                ]: Edge {
                    stroke: green;
                    from_x: edge[0];
                    from_y: edge[1];
                    to_x: edge[2];
                    to_y: edge[3];
                }

                // place every edges
                for edge in edges: Edge {
                    from_x: edge.from_x;
                    from_y: edge.from_y;
                    to_x: edge.to_x;
                    to_y: edge.to_y;
                }

                // temp bubble
                // bubble_b := TaskBubble {
                //     moved_to(x, y) => {
                //         debug(self.x, self.y);
                //     }
                //     x: pan_box.center_x - self.width / 2;
                //     y: pan_box.center_y - self.height / 2;
                //     task: {
                //         id: 55,
                //         title: "Meow Meow Meow",
                //         x: 123px,
                //         y: 123px,
                //     };
                // }

                // place every tasks
                for task in tasks: TaskBubble {
                    // todo: the task coord should be in the middle
                    x: pan_box.center_x + task.x - self.width / 2;
                    y: pan_box.center_y + task.y - self.height / 2;
                    task: task;
                    moved_to(x, y) => {
                        // TODO: The position isn't right
                        // oh I think the issue is because what moves isn't this task bubble but the dragable rectangle in the task bubble

                        // The backend manager needs to be updated to save the tasks at the right positions
                        // root.task_moved(task.id, self.x, self.y);
                    }
                    delete_clicked() => {
                        root.delete_task(task.id);
                    }
                    state_change_clicked(state) => {
                        root.change_state(task.id, state)
                    }
                }
            }
        }

        // button controls
        VerticalLayout {
            alignment: end;
            HorizontalBox {
                padding: 0px;
                Button {
                    text: "Center View";
                    clicked => {
                        pan_box.move_view_to(pan_box.center_x, pan_box.center_y);
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                title_le := LineEdit {
                    placeholder-text: "Title";
                }

                Button {
                    text: "Add";
                    clicked => {
                        root.add_task(
                            title_le.text,
                            0,
                            0,
                        );
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                Button {
                    text: "Load";
                    clicked => {
                        root.load("D:\\repositories\\apollo-roboto\\rust-firework\\tasks.json");
                    }
                }

                Button {
                    text: "Save";
                    clicked => {
                        root.save("D:\\repositories\\apollo-roboto\\rust-firework\\tasks.json");
                    }
                }
            }
        }
    }
}
