import { Button, VerticalBox, HorizontalBox, LineEdit, Palette } from "std-widgets.slint";
import { WorkBench, DragableRectangle } from "widgets/workbench.slint";
import { Styles } from "styles.slint";
import { Bubble } from "widgets/bubble.slint";
import { Edge } from "widgets/workbench_edge.slint";

enum MindTaskState {
    Todo,
    Doing,
    Done,
}

struct MindTask {
    id: int,
    title: string,
    state: MindTaskState,
    x: length,
    y: length,
    completion: float,
}

struct MindEdge {
    from_x: length,
    from_y: length,
    to_x: length,
    to_y: length,
}

enum TaskLoadingState {
    None, Loading, Error,
}
enum TaskSavingState {
    None, Saving, Error,
}
enum AppMode {
    None, SetParent, AddChildren,
}

component TaskBubble {
    in property <MindTask> task;
    in property <bool> extra_info: true;
    in property <brush> default_color: Styles.todo_color;
    in property <brush> todo_color: Styles.todo_color;
    in property <brush> doing_color: Styles.doing_color;
    in property <brush> done_color: Styles.done_color;
    in property <bool> active: false;
    out property <bool> dragged <=> dr.dragged;
    callback delete_clicked();
    callback state_change_clicked(state: MindTaskState);
    callback rename_clicked();
    callback set_parent_clicked();
    callback remove_parent_clicked();
    callback add_children_clicked();
    callback moved_by(x: length, y: length);
    callback clicked();
    dr := DragableRectangle {
        moved_by(x, y) => {
            root.moved_by(x, y);
        }
        clicked => {
            root.clicked();
        }
        ContextMenuArea {
            Menu {
                MenuItem {
                    title: "Rename";
                    activated => {
                        root.rename_clicked();
                    }
                }

                Menu {
                    title: "Set State";
                    MenuItem {
                        title: "To Do";
                        activated => {
                            root.state_change_clicked(MindTaskState.Todo);
                        }
                    }

                    MenuItem {
                        title: "Doing";
                        activated => {
                            root.state_change_clicked(MindTaskState.Doing);
                        }
                    }

                    MenuItem {
                        title: "Done";
                        activated => {
                            root.state_change_clicked(MindTaskState.Done);
                        }
                    }
                }

                MenuSeparator { }

                MenuItem {
                    title: "Set Parent";
                    activated => {
                        root.set_parent_clicked();
                    }
                }

                MenuItem {
                    title: "Remove Parent";
                    activated => {
                        root.remove_parent_clicked();
                    }
                }

                MenuItem {
                    title: "Add Child";
                    activated => {
                        root.add_children_clicked();
                    }
                }

                MenuSeparator { }

                MenuItem {
                    title: "Delete";
                    activated => {
                        root.delete_clicked();
                    }
                }
            }

            VerticalLayout {
                HorizontalLayout {
                    TouchArea {
                        width: 16px;
                        height: 16px;
                        Rectangle {
                            background: todo_color;
                        }

                        clicked => {
                            root.state_change_clicked(MindTaskState.Todo);
                        }
                    }

                    TouchArea {
                        width: 16px;
                        height: 16px;
                        Rectangle {
                            background: doing_color;
                        }

                        clicked => {
                            root.state_change_clicked(MindTaskState.Doing);
                        }
                    }

                    TouchArea {
                        width: 16px;
                        height: 16px;
                        Rectangle {
                            background: done_color;
                        }

                        clicked => {
                            root.state_change_clicked(MindTaskState.Done);
                        }
                    }

                    Rectangle {
                        horizontal-stretch: 1;
                    }

                    TouchArea {
                        width: 16px;
                        height: 16px;
                        Rectangle {
                            background: Styles.danger_color;
                        }

                        clicked => {
                            root.delete_clicked();
                        }
                    }
                }

                Bubble {
                    text: task.title;
                    background: task.state == MindTaskState.Todo ? todo_color //
                      : task.state == MindTaskState.Doing ? doing_color //
                      : task.state == MindTaskState.Done ? done_color // 
                      : default_color;
                    border-color: root.active ? Styles.active_color : black;
                    drop-shadow-color: dragged ? #00000055 : #00000000;
                    drop-shadow-blur: dragged ? 20px : 0px;
                    drop-shadow-offset-x: 5px;
                    drop-shadow-offset-y: 5px;
                    animate drop-shadow-color, drop-shadow-blur, drop-shadow-offset-x, drop-shadow-offset-y {
                        duration: 180ms;
                        easing: ease-in-out;
                    }
                }

                if extra_info:
            HorizontalLayout {
                    Text {
                        font-family: "Consolas";
                        text: Math.round(task.completion * 100) + "%";
                    }

                    Rectangle {
                        horizontal-stretch: 1;
                    }

                    Text {
                        font-family: "Consolas";
                        text: task.id;
                    }
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    in property <[MindTask]> tasks;
    in property <[MindEdge]> edges;
    in property <TaskLoadingState> task_loading_state: TaskLoadingState.None;
    in property <string> task_loading_error_message;
    in property <TaskSavingState> task_saving_state: TaskSavingState.None;
    in property <string> task_saving_error_message;
    in property <float> overall_progress: 0.0;
    out property <AppMode> mode: AppMode.None;
    in-out property <int> active_task: -1;
    callback load(path: string);
    callback save(path: string);
    callback undo();
    callback redo();
    callback create_task(title: string, x: length, y: length);
    callback set_parent_to_task(id: int, parent: int);
    callback unset_parent_from_task(id: int);
    callback delete_task(id: int);
    callback change_state(id: int, state: MindTaskState);
    callback task_moved(id: int, x: length, y: length);
    callback refresh_other();
    callback refresh_edges();
    public function refresh_all() {
        root.refresh_other();
        root.refresh_edges();
    }
    public function clear_active_task() {
        root.active_task = -1;
    }
    public function set_active_task(id: int) {
        root.active_task = id;
    }
    preferred-width: 600px;
    preferred-height: 600px;
    VerticalBox {
        alignment: LayoutAlignment.stretch;
        workbench := WorkBench {
            debugging: true;
            background: Styles.workbench_background_color;
            background_detail_color: Styles.workbench_background_details_color;
            workbench_clicked => {
                root.clear_active_task();
                root.mode = AppMode.None;
            }
            ContextMenuArea {
                Menu {
                    MenuItem {
                        title: "New Task";
                        activated => {
                            create_task("New Task", 0px, 0px);
                        }
                    }
                }
            }

            // place every edges
            for edge in edges: Edge {
                stroke: Styles.edge_color;
                stroke_width: 4px;
                from_x: edge.from_x;
                from_y: edge.from_y;
                to_x: edge.to_x;
                to_y: edge.to_y;
            }

            // TODO: add a line from the active task to the cursor
            if root.mode == AppMode.SetParent //
            || root.mode == AppMode.AddChildren:
            Edge {
                stroke: Styles.edge_color;
                stroke_width: 4px;
                from_x: 0;
                from_y: 0;
                to_x: workbench.center_x;
                to_y: workbench.center_y;
            }


            // temp bubble
            // bubble_b := TaskBubble {
            //     x: workbench.center_x + self.task.x - self.width / 2;
            //     y: workbench.center_y + self.task.y - self.height / 2;
            //     active: false;
            //     task: {
            //         id: 55,
            //         title: "Meow Meow Meow",
            //         x: 123px,
            //         y: 123px,
            //     };
            //     moved_by(x, y) => {
            //         self.task.x = x + self.task.x;
            //         self.task.y = y + self.task.y;
            //     }
            // }

            // place every tasks
            for task in tasks: TaskBubble {
                x: workbench.center_x + task.x - self.width / 2;
                y: workbench.center_y + task.y - self.height / 2;
                task: task;
                active: root.active_task == task.id;
                moved_by(x, y) => {
                    task.x = x + task.x;
                    task.y = y + task.y;
                    root.task_moved(task.id, task.x, task.y);
                }
                rename_clicked => {
                    //
                }
                delete_clicked() => {
                    root.delete_task(task.id);
                    root.clear_active_task();
                }
                state_change_clicked(state) => {
                    root.change_state(task.id, state)
                }
                set_parent_clicked => {
                    root.set_active_task(task.id);
                    root.mode = AppMode.SetParent;
                }
                remove_parent_clicked => {
                    root.unset_parent_from_task(task.id);
                }
                add_children_clicked => {
                    root.set_active_task(task.id);
                    root.mode = AppMode.AddChildren;
                }
                clicked => {
                    if root.mode == AppMode.SetParent {
                        root.set_parent_to_task(root.active_task, task.id);
                        root.mode = AppMode.None;
                        return;
                    }
                    if root.mode == AppMode.AddChildren {
                        root.set_parent_to_task(task.id, root.active_task);
                        root.mode = AppMode.None;
                        return;
                    }
                    root.set_active_task(task.id);
                }
            }
        }
        
    

        // button controls
        VerticalLayout {
            alignment: end;
            // debug row
            HorizontalBox {
                alignment: stretch;
                Text {
                    horizontal-stretch: 1;
                    horizontal-alignment: center;
                    text: root.mode == AppMode.None ? "Mode: None" //
                            : root.mode == AppMode.AddChildren ? "Mode: AddChildren" //
                            : root.mode == AppMode.SetParent ? "Mode: SetParent" //
                            : "Mode: AAAAAAAAAAAAA";
                }

                Text {
                    horizontal-stretch: 1;
                    horizontal-alignment: center;
                    text: "History Past/Future: TODO/TODO";
                }

                Text {
                    horizontal-stretch: 1;
                    horizontal-alignment: center;
                    text: "Active Task: #" + root.active_task;
                }

                Text {
                    horizontal-stretch: 1;
                    horizontal-alignment: center;
                    text: "Overall Progress: " + Math.round(root.overall_progress * 100) + "%";
                }
            }

            // button row
            HorizontalBox {
                padding: 0px;
                Button {
                    text: "Center View";
                    clicked => {
                        workbench.move_view_to(workbench.center_x, workbench.center_y);
                    }
                }

                Button {
                    text: "Clear Active";
                    clicked => {
                        root.clear_active_task();
                    }
                }

                Button {
                    text: "Reset Mode";
                    clicked => {
                        root.mode = AppMode.None;
                    }
                }

                Button {
                    text: "Refresh All";
                    clicked => {
                        root.refresh_all();
                    }
                }

                Button {
                    // TODO: this should be disabled if there is no past commands
                    text: "Undo";
                    clicked => {
                        root.undo();
                    }
                }

                Button {
                    // TODO: this should be disabled if there is no future commands
                    text: "Redo";
                    clicked => {
                        root.redo();
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                }

                Button {
                    text: "Load";
                    clicked => {
                        root.load("D:\\repositories\\apollo-roboto\\rust-firework\\resources\\sample_tasks.json");
                    }
                }

                Button {
                    text: "Save";
                    clicked => {
                        root.save("D:\\repositories\\apollo-roboto\\rust-firework\\resources\\sample_tasks.json");
                    }
                }
            }
        }
    }
}
