export enum AppMode {
    None, SetParent, AddChildren, AddDependency, DraggingSelected
}

export enum MindTaskState {
    Todo,
    Doing,
    Done,
}

export struct MindTask {
    id: int,
    title: string,
    notes: string,
    state: MindTaskState,
    x: length,
    y: length,
    parent_id: int,
    parent_index: int,
    childrens: [int],
    completion: float,
    selected: bool,
    blocked: bool,
    depends_on_indexes: [int],
}
