import { MindTaskState } from "models.slint";
import { Palette } from "std-widgets.slint";

export global Styles {
    in-out property <color> hyperlink: Palette.color-scheme == ColorScheme.dark //
        ? #8686fa : #0808fa;
    in-out property <color> todo_color: Palette.color-scheme == ColorScheme.dark //
        ? #333333 //
        : #b8b8b8;
    in-out property <color> doing_color: Palette.color-scheme == ColorScheme.dark //
        ? #2b599c //
        : #7199d4;
    in-out property <color> done_color: Palette.color-scheme == ColorScheme.dark //
        ? #186638 //
        : #5ab478;
    in-out property <color> danger_color: Palette.color-scheme == ColorScheme.dark //
        ? #ac372f //
        : #d85147;
    in-out property <color> selected_color: Palette.color-scheme == ColorScheme.dark //
        ? #ffa300 //
        : #ffa600;
    in-out property <color> active_color: Palette.color-scheme == ColorScheme.dark //
        ? #ffa300 //
        : #ffa600;
    in-out property <color> edge_color: Palette.color-scheme == ColorScheme.dark //
        ? #525281 //
        : #b0abd1;
    in-out property <color> temporary_edge_color: Palette.color-scheme == ColorScheme.dark //
        ? #7b88ac //
        : #645c75;
    in-out property <brush> workbench_background_color: Palette.color-scheme == ColorScheme.dark //
        ? #00000000 //
        : #00000000;
    in-out property <brush> workbench_background_details_color: Palette.color-scheme == ColorScheme.dark //
        ? #ffffff0c //
        : #00000014;
    public pure function color_from_state(state: MindTaskState) -> brush {
        if state == MindTaskState.Todo {
            return self.todo_color;
        }
        if state == MindTaskState.Doing {
            return self.doing_color;
        }
        if state == MindTaskState.Done {
            return self.done_color;
        }
        return self.todo_color;
    }
}
