export global Styles {
    in-out property <color> todo_color:     #333333;
    in-out property <color> doing_color:    #2b599c;
    in-out property <color> done_color:     #186638;
    in-out property <color> danger_color:   #ac372f;
    in-out property <color> selected_color: #ff8c00;
    in-out property <color> active_color:   #ffa500;
    in-out property <color> edge_color:     #525281;
    in-out property <brush> workbench_background_color:         #00000000;
    in-out property <brush> workbench_background_details_color: #ffffff0c;
}
