import {
    Button,
    VerticalBox,
    HorizontalBox,
    LineEdit,
    Palette,
    TextEdit,
    CheckBox,
    Switch,
} from "std-widgets.slint";
import { WorkBench } from "widgets/workbench.slint";
import { SelectionBoxKind } from "widgets/selection_rectangle.slint";
import { Styles, Func } from "global.slint";
import { AppMode, MindTask, MindTaskState } from "models.slint";
import { Edge } from "widgets/workbench_edge.slint";
import { TaskDetailPanel } from "widgets/task_detail_panel.slint";
import { MiddleProgressBar } from "widgets/middle_progress_bar.slint";
import { ThemeSwitch } from "widgets/theme_switch.slint";
import {
    FileDialogButton,
    FileDialogType,
    FileDialogButtonGlobal,
    FileDialogResultStatus,
    FileDialogFilter,
    FileDialogResult,
} from "widgets/file_dialog_button.slint";
import { AboutWindowContent } from "about.slint";
import { SelectionRectangle } from "widgets/selection_rectangle.slint";
import { DebugForIndex } from "widgets/debug_for_index.slint";
import { TaskBubble } from "widgets/task_bubble.slint";

export { HyperlinkGlobal } from "widgets/hyperlink.slint";
export { Func, FileDialogButtonGlobal }

enum TaskLoadingState {
    None, Loading, Error,
}
enum TaskSavingState {
    None, Saving, Error,
}

export component AppWindow inherits Window {
    in property <string> app_version;
    in property <bool> is_release;
    in-out property <[MindTask]> tasks;
    in property <TaskLoadingState> task_loading_state: TaskLoadingState.None;
    in property <string> task_loading_error_message;
    in property <TaskSavingState> task_saving_state: TaskSavingState.None;
    in property <string> task_saving_error_message;
    in property <float> overall_progress: 0.0;
    in property <int> active_task_index: -1;
    in property <int> history_past_count;
    in property <int> history_future_count;
    in property <int> history_limit;
    in property <string> last_command;
    in-out property <bool> debug_info: !is_release;
    out property <AppMode> mode: AppMode.None;
    out property <int> hovered_task_index: -1;
    in-out property <string> current_file_path: "";
    out property <bool> has_focus <=> window_focus.has-focus;
    out property <length> dragging_start_pos_x;
    out property <length> dragging_start_pos_y;
    in-out property <bool> show_menu_bar: true;
    in-out property <bool> show_dependency_edges: false;
    callback quit();
    callback refresh_other();
    callback refresh_tasks();
    callback open_file_picked(path: string);
    callback save_file_picked(path: string);
    callback undo();
    callback redo();
    callback create_task(title: string, x: length, y: length);
    callback create_task_with_parent(parent_id: int, title: string, x: length, y: length);
    callback set_parent_to_task(id: int, parent: int);
    callback unset_parent_from_task(id: int);
    callback add_dependency_to_task(id: int, depends_on: int);
    callback remove_dependency_from_task(id: int, depends_on: int); // TODO: call this to remove individual dependencies
    callback remove_all_dependencies_from_task(id: int);
    callback duplicate_selected();
    callback delete_task(id: int);
    callback delete_selected();
    callback change_state(id: int, state: MindTaskState);
    /// called when the selection movement has been dropped, x and y are relative position to the drag start
    callback selected_move_dropped(x: length, y: length);
    callback rename_task(id: int, title: string);
    callback set_task_notes(id: int, description: string);
    callback set_active_task(id: int, keep_selection: bool);
    callback clear_active_task(keep_selected: bool);
    callback clear_selection();
    callback select_all();
    callback set_selection_from_box(length, length, length, length);
    callback add_selection_from_box(length, length, length, length);
    callback remove_selection_from_box(length, length, length, length);
    // callback add_to_selection(id: int);
    // callback remove_from_selection(id: int);
    public function refresh_all() {
        root.refresh_tasks();
        root.refresh_other();
    }
    public function open_file(path: string) {
        root.current_file_path = path;
        root.open_file_picked(path);
    }
    public function open() {
        let result = FileDialogButtonGlobal.open("Open File", "", [{ text: "TodoGraph", extensions : ["todog"] }], "", FileDialogType.load);
        if result.status == FileDialogResultStatus.picked {
            let file = result.file;
            root.open_file_picked(file);
            root.current_file_path = file;
        }
    }
    /// Save to the current file if set, or opens the save as dialog to pick a location
    public function save() {
        if root.current_file_path != "" {
            root.save_file_picked(root.current_file_path);
            return;
        }
        root.save_as();
    }
    public function save_as() {
        let result = FileDialogButtonGlobal.open("Save As", "", [{ text: "TodoGraph", extensions : ["todog"] }], root.current_file_path, FileDialogType.save);
        if result.status == FileDialogResultStatus.picked {
            let file = result.file;
            root.save_file_picked(file);
            root.current_file_path = file;
        }
    }
    public function new_project() {
        root.current_file_path = "";
        root.open_file_picked("");
    }
    preferred-width: 800px;
    preferred-height: 600px;
    forward-focus: window_focus;
    if root.show_menu_bar:
    MenuBar {
        Menu {
            title: "File";
            MenuItem {
                title: "New";
                activated => {
                    root.new_project();
                }
            }

            MenuItem {
                title: "Open...";
                activated => {
                    root.open();
                };
            }

            // Menu {
            //     title: "Open recent";
            //     for i in ["1", "2", "3", "4"]: MenuItem {
            //         title: i;
            //         activated => {
            //             root.open_file(i);
            //         };
            //     }
            //     MenuSeparator { }

            //     MenuItem {
            //         title: "Clear";
            //         activated => {
            //             debug("TODO");
            //         }
            //     }
            // }

            MenuSeparator { }

            MenuItem {
                title: "Save";
                activated => {
                    root.save();
                };
            }

            MenuItem {
                title: "Save as...";
                activated => {
                    root.save_as();
                };
            }

            MenuSeparator { }

            // MenuItem {
            //     title: "Import...";
            //     activated => {
            //         debug("TODO");
            //     }
            // }

            // Menu {
            //     title: "Export";
            //     MenuItem {
            //         title: "SVG...";
            //         activated => {
            //             debug("TODO");
            //         }
            //     }
            // }

            // MenuSeparator { }

            MenuItem {
                title: "Quit";
                activated => {
                    // TODO: Check if the file has changes first before quitting
                    root.quit();
                }
            }
        }

        Menu {
            title: "Edit";
            MenuItem {
                title: "Undo";
                enabled: root.history_past_count > 0;
                activated => {
                    root.undo();
                }
            }

            MenuItem {
                title: "Redo";
                enabled: root.history_future_count > 0;
                activated => {
                    root.redo();
                }
            }

            MenuSeparator { }

            MenuItem {
                title: "Settings";
                activated => {
                    debug("TODO");
                }
            }

            MenuItem {
                title: "Toggle theme";
                checkable: true;
                activated => {
                    if self.checked {
                        Palette.color-scheme = ColorScheme.light;
                    } else {
                        Palette.color-scheme = ColorScheme.dark;
                    }
                }
            }

            MenuItem {
                title: "Toggle dependency edges";
                checkable: true;
                activated => {
                    root.show_dependency_edges = self.checked;
                }
            }
        }

        Menu {
            title: "View";
            MenuItem {
                title: "Center view";
                activated => {
                    workbench.move_view_to(workbench.center_x, workbench.center_y);
                }
            }

            MenuItem {
                title: "Reset zoom";
                activated => {
                    workbench.reset_zoom();
                }
            }
        }

        Menu {
            title: "Help";
            MenuItem {
                title: "Toggle debug";
                checkable: true;
                checked <=> root.debug_info;
            }

            MenuItem {
                title: "About";
                activated => {
                    about_window.show();
                }
            }
        }
    }
    window_focus := FocusScope {
        key-pressed(event) => {
            if event.text.to-lowercase() == "d" && event.modifiers.shift {
                root.duplicate_selected();
                return EventResult.accept;
            }
            if event.text.to-lowercase() == "a" && event.modifiers.control && event.modifiers.shift {
                root.clear_selection();
                return EventResult.accept;
            }
            if event.text.to-lowercase() == "a" && event.modifiers.control {
                root.select_all();
                return EventResult.accept;
            }
            if event.text.to-lowercase() == "z" && event.modifiers.control && event.modifiers.shift {
                root.redo();
                return EventResult.accept;
            }
            if event.text.to-lowercase() == "z" && event.modifiers.control {
                root.undo();
                return EventResult.accept;
            }
            if event.text.to-lowercase() == "s" && event.modifiers.control && event.modifiers.shift {
                root.save_as();
                return EventResult.accept;
            }
            if event.text.to-lowercase() == "s" && event.modifiers.control {
                root.save();
                return EventResult.accept;
            }
            if event.text.to-lowercase() == "o" && event.modifiers.control {
                root.open();
                return EventResult.accept;
            }
            if event.text == Key.Delete {
                root.delete_selected();
                return EventResult.accept;
            }
            if event.text == "1" && root.active_task_index >= 0 {
                root.change_state(root.tasks[root.active_task_index].id, MindTaskState.Todo);
                return EventResult.accept;
            }
            if event.text == "2" && root.active_task_index >= 0 {
                root.change_state(root.tasks[root.active_task_index].id, MindTaskState.Doing);
                return EventResult.accept;
            }
            if event.text == "3" && root.active_task_index >= 0 {
                root.change_state(root.tasks[root.active_task_index].id, MindTaskState.Done);
                return EventResult.accept;
            }
            if event.text == Key.Escape && root.mode != AppMode.None {
                root.mode = AppMode.None;
                return EventResult.accept;
            }
            return EventResult.reject;
        }
    }

    about_window := PopupWindow {
        width: root.width;
        height: root.height;
        close-policy: PopupClosePolicy.no-auto-close;
        Rectangle {
            background: #00000055;
            TouchArea {
                clicked => {
                    about_window.close();
                }
            }
        }

        AboutWindowContent {
            version: root.app_version + " (" + (root.is_release ? "Release" : "Development") + ")";
        }
    }

    HorizontalBox {
        alignment: stretch;
        Rectangle {
            workbench := WorkBench {
                horizontal-stretch: 1;
                debug_info: root.debug_info;
                background: Styles.workbench_background_color;
                background_detail_color: Styles.workbench_background_details_color;
                selection_rectangle_border: Styles.selection_rectangle_border;
                selection_rectangle_fill: Styles.selection_rectangle_fill;
                workbench_clicked => {
                    root.focus();
                    root.clear_selection();
                    root.mode = AppMode.None;
                }
                workbench_double_clicked => {
                    if root.mode == AppMode.None {
                        root.create_task("New Task", workbench.mouse_pos_x, workbench.mouse_pos_y);
                    }
                }
                workbench_box_selected(x1, y1, x2, y2, kind) => {
                    root.mode = AppMode.None;
                    if kind == SelectionBoxKind.Set {
                        root.set_selection_from_box(x1, y1, x2, y2);
                        return;
                    }
                    if kind == SelectionBoxKind.Add {
                        root.add_selection_from_box(x1, y1, x2, y2);
                        return;
                    }
                    if kind == SelectionBoxKind.Sub {
                        root.remove_selection_from_box(x1, y1, x2, y2);
                        return;
                    }
                }
                changed has-hover => {
                    if self.has-hover {
                        root.hovered_task_index = -1;
                    }
                }
                ContextMenuArea {
                    Menu {
                        MenuItem {
                            title: "New Task";
                            activated => {
                                root.create_task("New Task", workbench.mouse_pos_x, workbench.mouse_pos_y);
                            }
                        }

                        MenuItem {
                            title: "Delete";
                                // enabled: root.has_selection // TODO
                                activated => {
                                root.delete_selected();
                            }
                        }
                    }
                }

                // place dependency edges
                if root.show_dependency_edges: Rectangle {
                    for task in tasks: Rectangle {
                        for dependency_index in task.depends_on_indexes: //
                        Edge {
                            // x and y adds an offset to the mouse if it is being dragged
                            stroke: Styles.dependency_edge_color;
                            stroke_width: 4px;
                            from_x: task.x + (root.mode == AppMode.DraggingSelected && task.selected ? workbench.mouse_pos_x - root.dragging_start_pos_x : 0);
                            from_y: task.y + (root.mode == AppMode.DraggingSelected && task.selected ? workbench.mouse_pos_y - root.dragging_start_pos_y : 0);
                            to_x: tasks[dependency_index].x + (root.mode == AppMode.DraggingSelected && tasks[dependency_index].selected ? workbench.mouse_pos_x - root.dragging_start_pos_x : 0);
                            to_y: tasks[dependency_index].y + (root.mode == AppMode.DraggingSelected && tasks[dependency_index].selected ? workbench.mouse_pos_y - root.dragging_start_pos_y : 0);
                        }
                    }
                }

                // place parenting edges
                for task in tasks: //
                    Rectangle {
                    if task.parent_index != -1:
                    Edge {
                        // x and y adds an offset to the mouse if it is being dragged
                        stroke: Styles.parenting_edge_color_child_side;
                        stroke_width: 4px;
                        from_x: task.x + (root.mode == AppMode.DraggingSelected && task.selected ? workbench.mouse_pos_x - root.dragging_start_pos_x : 0);
                        from_y: task.y + (root.mode == AppMode.DraggingSelected && task.selected ? workbench.mouse_pos_y - root.dragging_start_pos_y : 0);
                        to_x: tasks[task.parent_index].x + (root.mode == AppMode.DraggingSelected && tasks[task.parent_index].selected ? workbench.mouse_pos_x - root.dragging_start_pos_x : 0);
                        to_y: tasks[task.parent_index].y + (root.mode == AppMode.DraggingSelected && tasks[task.parent_index].selected ? workbench.mouse_pos_y - root.dragging_start_pos_y : 0);
                    }
                }

                // preview edge for user feedback
                // will snap to the hovered task if any
                if root.mode == AppMode.SetParent //
                || root.mode == AppMode.AddChildren //
                || root.mode == AppMode.AddDependency:
                    Edge {
                    stroke: Styles.temporary_edge_color;
                    stroke_width: 4px;
                    from_x: tasks[active_task_index].x;
                    from_y: tasks[active_task_index].y;
                    to_x: root.hovered_task_index >= 0 //
                            ? root.tasks[root.hovered_task_index].x //
                            : workbench.mouse_pos_x;
                    to_y: root.hovered_task_index >= 0 //
                            ? root.tasks[root.hovered_task_index].y //
                            : workbench.mouse_pos_y;
                }

                // temp bubble
                // bubble_a := TaskBubble {
                //     x: workbench.center_x + self.task.x - self.width / 2;
                //     y: workbench.center_y + self.task.y - self.height / 2;
                //     active: false;
                //     debug_info: root.debug_info;
                //     task: {
                //         id: 55,
                //         title: "A",
                //         x: 250px,
                //         y: 350px,
                //         completion: 50%,
                //         childrens: [1, 2, 3, 4],
                //         state: MindTaskState.Doing,
                //     };
                //     moved_by(x, y) => {
                //         self.task.x = x + self.task.x;
                //         self.task.y = y + self.task.y;
                //     }
                // }

                // place every tasks
                for task[index] in tasks: TaskBubble {
                    // x and y adds an offset to the mouse if it is being dragged
                    x: workbench.center_x + task.x - self.width / 2 + ( //
                            root.mode == AppMode.DraggingSelected && task.selected //
                            ? workbench.mouse_pos_x - root.dragging_start_pos_x //
                            : 0);
                    y: workbench.center_y + task.y - self.height / 2 + ( //
                            root.mode == AppMode.DraggingSelected && task.selected //
                            ? workbench.mouse_pos_y - root.dragging_start_pos_y //
                            : 0);
                    task: task;
                    active: root.active_task_index == index;
                    debug_info: root.debug_info;
                    changed has-hover => {
                        if self.has-hover {
                            root.hovered_task_index = index;
                        }
                    }
                    delete_clicked() => {
                        root.delete_task(task.id);
                    }
                    state_change_clicked(state) => {
                        root.change_state(task.id, state)
                    }
                    set_parent_clicked => {
                        root.set_active_task(task.id, false);
                        root.mode = AppMode.SetParent;
                    }
                    remove_parent_clicked => {
                        root.unset_parent_from_task(task.id);
                    }
                    add_children_clicked => {
                        root.set_active_task(task.id, false);
                        root.mode = AppMode.AddChildren;
                    }
                    add_dependency_clicked => {
                        root.set_active_task(task.id, false);
                        root.mode = AppMode.AddDependency;
                    }
                    remove_all_dependencies_clicked => {
                        root.remove_all_dependencies_from_task(task.id);
                    }
                    new_children_clicked => {
                        root.create_task_with_parent(task.id, "New Task", workbench.mouse_pos_x, workbench.mouse_pos_y);
                    }
                    left_mouse_down(event) => {
                        root.focus();
                        if root.mode == AppMode.AddDependency {
                            root.add_dependency_to_task(root.tasks[active_task_index].id, task.id);
                            root.mode = AppMode.None;
                            return;
                        }
                        if root.mode == AppMode.SetParent {
                            root.set_parent_to_task(root.tasks[active_task_index].id, task.id);
                            root.mode = AppMode.None;
                            return;
                        }
                        if root.mode == AppMode.AddChildren {
                            root.set_parent_to_task(task.id, root.tasks[active_task_index].id);
                            root.mode = AppMode.None;
                            return;
                        }

                        // handle Blender style selection clicks
                        if self.active && event.modifiers.shift {
                            root.clear_active_task(false);
                        } else if !self.active && event.modifiers.shift {
                            root.set_active_task(task.id, true);
                        } else if !task.selected && !event.modifiers.shift {
                            root.set_active_task(task.id, false);
                        }

                        // start moving selected
                        if !event.modifiers.shift {
                            root.mode = AppMode.DraggingSelected;
                            root.dragging_start_pos_x = workbench.mouse_pos_x;
                            root.dragging_start_pos_y = workbench.mouse_pos_y;
                        }
                    }
                    left_mouse_up(event) => {
                        if root.mode == AppMode.DraggingSelected {
                            if workbench.mouse_pos_x != root.dragging_start_pos_x || workbench.mouse_pos_y != root.dragging_start_pos_y {
                                root.selected_move_dropped(workbench.mouse_pos_x - root.dragging_start_pos_x, workbench.mouse_pos_y - root.dragging_start_pos_y);
                            } else {

                                // handle Blender style selection clicks
                                if !event.modifiers.shift {
                                    root.set_active_task(task.id, false);
                                }
                            }
                            root.mode = AppMode.None;
                            return;
                        }
                    }
                }
            }

            if root.debug_info:
            DebugForIndex {
                active_task_id: root.active_task_index >= 0 ? root.tasks[root.active_task_index].id : root.active_task_index;
                app_mode: root.mode;
                app_version: root.app_version;
                current_file_path: root.current_file_path;
                history_future_count: root.history_future_count;
                history_limit: root.history_limit;
                history_past_count: root.history_past_count;
                hovered_task_id: root.hovered_task_index >= 0 ? root.tasks[root.hovered_task_index].id : root.hovered_task_index;
                index_has_focus: root.has_focus;
                is_release: root.is_release;
                last_command: root.last_command;
                num_of_tasks: root.tasks.length;
                overall_progress: root.overall_progress;
                workbench_mouse_pos_x: workbench.mouse_pos_x;
                workbench_mouse_pos_y: workbench.mouse_pos_y;
                workbench_view_pos_x: workbench.view_pos_x;
                workbench_view_pos_y: workbench.view_pos_y;
                workbench_zoom: workbench.zoom;
            }
        }

        if root.active_task_index >= 0:
        TaskDetailPanel {
            task: root.tasks[active_task_index];
            show: root.active_task_index >= 0;
            width: 380px;
            delete_clicked => {
                root.delete_task(root.tasks[active_task_index].id);
            }
            title_changed(value) => {
                root.tasks[active_task_index].title = value;
            }
            title_submitted(value) => {
                root.rename_task(root.tasks[active_task_index].id, value);
            }
            notes_submitted(value) => {
                root.set_task_notes(root.tasks[active_task_index].id, value);
            }
            state_changed(value) => {
                root.change_state(root.tasks[active_task_index].id, value);
            }
            lock_released => {
                root.focus();
            }
        }
    }
}
