import { VerticalBox, HorizontalBox, LineEdit, Button, TextEdit, ComboBox, Palette } from "std-widgets.slint";
import { MindTask, MindTaskState } from "../models.slint";
import { Styles } from "../styles.slint";

component StateButton inherits Rectangle {
    in property <bool> active: true;
    in property <MindTaskState> state;
    callback clicked();
    height: 35px;
    opacity: active ? 100% : ta.has-hover ? 75% : 50%;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    border-radius: 4px;
    background: Styles.color_from_state(root.state);
    ta := TouchArea {
        clicked => {
            root.clicked();
        }
    }

    Text {
        horizontal-alignment: center;
        vertical-alignment: center;
        text: state == MindTaskState.Todo ? "Todo" //
            : state == MindTaskState.Doing ? "Doing" //
            : state == MindTaskState.Done ? "Done" //
            : "AAAAAAAA";
    }
}

/// Takes full focus of the application
/// the text is submitted when the focus is lost
/// any click outside makes it lose focus
/// accepted (enter) will make it unfocus
/// This behavior is inspired from Blender
/// TODO: tab should go to the next focus element
component PriorityFocusLineEdit {
    in property <string> text;
    in property <string> placeholder-text;
    in property <bool> enabled: true;
    in property <InputType> input-type;
    out property <bool> has_changed: false;
    out property <bool> has-focus;
    out property <string> original_text;
    callback changed(string);
    callback submitted(string);
    property <bool> popup_opened: false;
    /// cancel the interaction
    public function cancel() {
        fake_lineedit.text = original_text;
        root.popup_opened = false;
        popup.close();
        root.changed(original_text);
    }
    /// submit the change in the text
    function submit(text: string) {
        fake_lineedit.text = text;
        root.has_changed = false;
        root.original_text = text;
        root.popup_opened = false;
        root.submitted(text);
        popup.close();
    }
    init => {
        root.original_text = text;
    }
    changed text => {
        fake_lineedit.text = root.text;
    }
    fake_lineedit := LineEdit {
        opacity: popup_opened ? 0% : 100%;
        width: parent.width;
        text: root.text;
        enabled: root.enabled;
        input-type: root.input-type;
        placeholder-text: root.placeholder-text;
        changed has-focus => {
            if self.has-focus {
                self.clear-focus();
                root.popup_opened = true;
                popup.show();
            }
        }
    }

    popup := PopupWindow {
        close-policy: PopupClosePolicy.no-auto-close;
        // Size Should be the full window but 100% doesn't work in version 1.13
        width: 10000px;
        height: 10000px;
        init => {
            real_lineedit.focus();
            real_lineedit.select-all();
        }
        TouchArea {
            mouse-cursor: MouseCursor.text;
            clicked => {
                real_lineedit.clear-focus();
            }
        }

        real_lineedit := LineEdit {
            text: root.text;
            width: fake_lineedit.width;
            x: fake_lineedit.absolute-position.x;
            y: fake_lineedit.absolute-position.y;
            enabled: root.enabled;
            input-type: root.input-type;
            placeholder-text: root.placeholder-text;
            key-pressed(event) => {
                if (event.text == Key.Escape) {
                    root.cancel();
                    return EventResult.accept;
                }
                return EventResult.reject;
            }
            accepted(text) => {
                self.clear-focus();
            }
            edited(text) => {
                root.has_changed = true;
                root.changed(text);
            }
            changed has-focus => {
                root.has-focus = self.has-focus;
                if !self.has-focus && root.has_changed {
                    root.submit(text);
                    return;
                }
                if !self.has-focus {
                    root.popup_opened = false;
                    popup.close();
                }
            }
        }
    }
}

export component TaskDetailPanel inherits Rectangle {
    in property <MindTask> task;
    in property <bool> show: false;
    callback title_changed(string);
    callback title_submitted(string);
    callback description_changed(string);
    callback state_changed(MindTaskState);
    callback delete_clicked();
    if !root.show:
    VerticalBox {
        alignment: center;
        Text {
            font-family: "Consolas";
            horizontal-alignment: center;
            text: "Select a task";
        }
    }
    if root.show:
    VerticalBox {
        padding: 0;
        alignment: stretch;
        Text {
            font-family: "Consolas";
            text: "Id: #" + task.id;
        }

        HorizontalBox {
            padding: 0;
            Text {
                font-family: "Consolas";
                vertical-alignment: center;
                text: "Title";
            }

            PriorityFocusLineEdit {
                text: task.title;
                changed(text) => {
                    root.title_changed(text);
                }
                submitted(text) => {
                    root.title_submitted(text);
                }
            }
        }

        HorizontalBox {
            padding: 0;
            // TODO: might change this to a simple combo box
            StateButton {
                state: MindTaskState.Todo;
                active: root.task.state == MindTaskState.Todo;
                clicked => {
                    root.state_changed(MindTaskState.Todo);
                }
            }

            StateButton {
                state: MindTaskState.Doing;
                active: root.task.state == MindTaskState.Doing;
                clicked => {
                    root.state_changed(MindTaskState.Doing);
                }
            }

            StateButton {
                state: MindTaskState.Done;
                active: root.task.state == MindTaskState.Done;
                clicked => {
                    root.state_changed(MindTaskState.Done);
                }
            }
        }

        Text {
            font-family: "Consolas";
            text: "Description:";
        }

        TextEdit {
            vertical-stretch: 1;
            // TODO: text: task.description;
            edited(text) => {
                //
            }
        }

        // Text {
        //     font-family: "Consolas";
        //     text: "Created: " + root.task.creation_date;
        // }

        // Text {
        //     font-family: "Consolas";
        //     text: root.task.has_completion_date //
        //         ? "Completed: None" //
        //         : "Completed: " + root.task.completion_date;
        // }

        Text {
            // TODO: would be cool to click so you can navigate to the parent
            font-family: "Consolas";
            text: root.task.parent_id == -1 //
                ? "Parent: None" //
                : "Parent: #" + root.task.parent_id;
        }

        Text {
            font-family: "Consolas";
            text: "Num of childrens: " + root.task.childrens.length;
        }

        Text {
            font-family: "Consolas";
            text: "Position: (" + root.task.x / 1px + ", " + root.task.y / 1px + ")";
        }

        Text {
            font-family: "Consolas";
            text: "Completion: " + Math.round(root.task.completion * 100) + "%";
        }

        HorizontalBox {
            padding: 0;
            alignment: end;
            Button {
                text: "Delete";
                clicked => {
                    root.delete_clicked();
                }
            }
        }
    }
}
