import { SelectionRectangle } from "selection_rectangle.slint";
import { Palette, Button } from "std-widgets.slint";

export component DragableRectangle inherits Rectangle {
    out property <bool> dragged: false;
    out property <bool> has-hover <=> ta.has-hover;
    callback moved_by(x: length, y: length);
    callback clicked();
    callback released();
    callback pointer-event(PointerEvent);
    ta := TouchArea {
        moved => {
            root.dragged = true;
            root.moved_by(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
        }
        clicked => {
            if root.dragged == false {
                root.clicked();
            }
        }
        pointer-event(event) => {
            if event.button == PointerEventButton.left && event.kind == PointerEventKind.up && root.dragged == true {
                root.dragged = false;
                root.released();
                return;
            }
            root.pointer-event(event);
        }
    }

    @children
}

component WorkAreaDebugLimit inherits Rectangle {
    in property <brush> line_color: #282828;
    in property <length> line_length: 25px;
    in property <length> line_thickness: 2px;
    // center horizontal
    Rectangle {
        background: line_color;
        width: line_length * 2;
        height: line_thickness;
    }
    // center vertical
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length * 2;
    }
    // top left corner
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: 0;
        y: 0;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: 0;
        y: 0;
    }
    // top right corner
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: root.width - self.width;
        y: 0;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: root.width - self.width;
        y: 0;
    }
    // bottom left corner
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: 0;
        y: root.height - self.height;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: 0;
        y: root.height - self.height;
    }
    // bottom right corner
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: root.width - self.width;
        y: root.height - self.height;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: root.width - self.width;
        y: root.height - self.height;
    }
}

export component WorkBench inherits Rectangle {
    in property <length> work_area_width: 5000px;
    in property <length> work_area_height: 5000px;
    in property <bool> debug_info: false;
    in property <bool> show_position: true;
    in property <image> background_detail_image: @image-url("../assets/point_tile_c_150x150.png");
    in property <brush> background_detail_color: #ffffff;
    in property <color> selection_rectangle_border: Palette.accent-background;
    in property <color> selection_rectangle_fill: #00000000;
    out property <bool> has-hover <=> ta_behind.has-hover;
    out property <bool> is_panning: false;
    out property <length> center_x: work_area.width / 2;
    out property <length> center_y: work_area.height / 2;
    // View position x from the center of the viewport
    out property <length> view_pos_x;
    // View position y from the center of the viewport
    out property <length> view_pos_y;
    /// Mouse position x relative from the center of the workbench
    out property <length> mouse_pos_x: ta_above.mouse-x - root.center_x;
    /// Mouse position y relative from the center of the workbench
    out property <length> mouse_pos_y: ta_above.mouse-y - root.center_y;
    out property <length> panning_start_y;
    out property <length> panning_start_x;
    /// Is the user performing a selection
    out property <bool> is_selecting: false;
    out property <length> selection_start_x;
    out property <length> selection_start_y;
    callback moved_by(x: length, y: length);
    callback workbench_clicked();
    callback workbench_double_clicked();
    callback workbench_box_selected(length, length, length, length);
    public function move_view_to(x: length, y: length) {
        work_area.x = root.width / 2 - x;
        work_area.y = root.height / 2 - y;
        root.view_pos_x = -(center_x + work_area.x - root.width / 2);
        root.view_pos_y = -(center_y + work_area.y - root.height / 2);
        root.moved_by(x, y);
    }
    clip: true;
    border-color: black;
    border-width: 1px;
    border-radius: 6px;
    init => {
        root.move_view_to(root.center_x, root.center_y);
    }

    // movable rectangle containing the childrens
    work_area := Rectangle {
        width: root.work_area_width;
        height: root.work_area_height;
        Image {
            colorize: root.background_detail_color;
            source: root.background_detail_image;
            vertical-tiling: ImageTiling.repeat;
            horizontal-tiling: ImageTiling.repeat;
            width: parent.width;
            height: parent.height;
        }

        if debug_info:
        WorkAreaDebugLimit {
            line_color: root.background_detail_color;
        }

        ta_above := TouchArea {
            // this TouchArea tracks the mouse position above all childrens
            mouse-cursor: root.is_panning ? MouseCursor.grabbing : MouseCursor.default;

            ta_behind := TouchArea {
                // this TouchArea handles all events behind the childrens, aka all actions on the workbench
                mouse-cursor: root.is_panning ? MouseCursor.grabbing : MouseCursor.default;
                double-clicked => {
                    if root.is_panning {
                        return;
                    }
                    root.workbench_double_clicked();
                }
                pointer-event(event) => {
                    if event.button == PointerEventButton.left && event.kind == PointerEventKind.down {
                        if root.is_selecting == false {
                            root.selection_start_x = self.mouse-x - root.center_x;
                            root.selection_start_y = self.mouse-y - root.center_y;
                            root.is_selecting = true;
                        }
                        return;
                    }
                    if event.button == PointerEventButton.left && event.kind == PointerEventKind.up {
                        // check if the cursor moved at all, no movement shouldn't trigger the selected callback
                        if root.selection_start_x == self.mouse-x - root.center_x && root.selection_start_y == self.mouse-y - root.center_y {
                            root.is_selecting = false;
                            root.workbench_clicked();
                            return;
                        }
                        root.workbench_box_selected(
                                root.selection_start_x,
                                root.selection_start_y,
                                self.mouse-x - root.center_x,
                                self.mouse-y - root.center_y //
                            );
                        root.is_selecting = false;
                        return;
                    }
                    if event.button == PointerEventButton.middle && event.kind == PointerEventKind.down {
                        root.is_panning = true;
                        root.panning_start_x = self.mouse-x;
                        root.panning_start_y = self.mouse-y;
                        return;
                    }
                    if event.button == PointerEventButton.middle && event.kind == PointerEventKind.up {
                        root.is_panning = false;
                        return;
                    }
                    if event.kind == PointerEventKind.move {
                        // owo <- this comment was written without my explicit consent, I do not agree with those words
                        if root.is_panning {
                            work_area.x = self.mouse-x - root.panning_start_x + work_area.x;
                            work_area.y = self.mouse-y - root.panning_start_y + work_area.y;
                            root.view_pos_x = -(root.center_x + work_area.x - root.width / 2);
                            root.view_pos_y = -(root.center_y + work_area.y - root.height / 2);
                            root.moved_by(self.mouse-x - root.panning_start_x, self.mouse-y - root.panning_start_y);
                        }
                        return;
                    }
                }
            }

            @children
        }

        if root.is_selecting:
        SelectionRectangle {
            anchor_x: root.selection_start_x + root.center_x;
            anchor_y: root.selection_start_y + root.center_y;
            mouse_x: root.mouse_pos_x + root.center_x;
            mouse_y: root.mouse_pos_y + root.center_y;
            border-color: root.selection_rectangle_border;
            background: root.selection_rectangle_fill;
        }
    }
}
