export component DragableRectangle inherits Rectangle {
    out property <bool> dragged: false;
    out property <bool> has-hover <=> ta.has-hover;
    callback moved_by(x: length, y: length);
    callback clicked();
    callback released();
    ta := TouchArea {
        moved => {
            root.dragged = true;
            root.moved_by(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
        }
        clicked => {
            if root.dragged == false {
                root.clicked();
            }
        }
        pointer-event(event) => {
            if event.button == PointerEventButton.left && event.kind == PointerEventKind.up && root.dragged == true {
                root.dragged = false;
                root.released();
            }
        }
    }

    @children
}

component WorkAreaDebugLimit inherits Rectangle {
    in property <brush> line_color: #282828;
    in property <length> line_length: 25px;
    in property <length> line_thickness: 2px;
    // center horizontal
    Rectangle {
        background: line_color;
        width: line_length * 2;
        height: line_thickness;
    }
    // center vertical
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length * 2;
    }
    // top left corner
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: 0;
        y: 0;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: 0;
        y: 0;
    }
    // top right corner
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: root.width - self.width;
        y: 0;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: root.width - self.width;
        y: 0;
    }
    // bottom left corner
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: 0;
        y: root.height - self.height;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: 0;
        y: root.height - self.height;
    }
    // bottom right corner 
    Rectangle {
        background: line_color;
        width: line_thickness;
        height: line_length;
        x: root.width - self.width;
        y: root.height - self.height;
    }

    Rectangle {
        background: line_color;
        width: line_length;
        height: line_thickness;
        x: root.width - self.width;
        y: root.height - self.height;
    }
}

export component WorkBench inherits Rectangle {
    in property <length> work_area_width: 5000px;
    in property <length> work_area_height: 5000px;
    in property <bool> debug_info: false;
    in property <bool> show_position: true;
    in property <image> background_detail_image: @image-url("../assets/point_tile_c_150x150.png");
    in property <brush> background_detail_color: #ffffff;
    out property <bool> has-hover <=> ta.has-hover;
    out property <bool> dragged: false;
    out property <length> center_x: work_area.width / 2;
    out property <length> center_y: work_area.height / 2;
    // View position x from the center of the viewport
    out property <length> view_pos_x;
    // View position y from the center of the viewport
    out property <length> view_pos_y;
    /// Mouse position x relative from the center of the workbench
    out property <length> mouse_pos_x;
    /// Mouse position y relative from the center of the workbench
    out property <length> mouse_pos_y;
    callback moved_by(x: length, y: length);
    callback workbench_clicked();
    callback workbench_double_clicked();
    public function move_view_to(x: length, y: length) {
        work_area.x = root.width / 2 - x;
        work_area.y = root.height / 2 - y;
        root.view_pos_x = -(center_x + work_area.x - root.width / 2);
        root.view_pos_y = -(center_y + work_area.y - root.height / 2);
        root.moved_by(x, y);
    }
    clip: true;
    border-color: black;
    border-width: 1px;
    border-radius: 6px;
    init => {
        // initial call to move to the center prevents a jump when the workbench is resized
        // or at least I think it changes the origin to the top left somehow, not sure what's going on
        root.move_view_to(root.center_x, root.center_y);
    }

    // movable rectangle containing the childrens
    work_area := Rectangle {
        width: root.work_area_width;
        height: root.work_area_height;
        Image {
            colorize: root.background_detail_color;
            source: root.background_detail_image;
            vertical-tiling: ImageTiling.repeat;
            horizontal-tiling: ImageTiling.repeat;
            width: parent.width;
            height: parent.height;
        }

        ta := TouchArea {
            mouse-cursor: root.dragged ? MouseCursor.grabbing : MouseCursor.default;
            moved => {
                root.dragged = true;
                work_area.x = self.mouse-x - self.pressed-x + work_area.x;
                work_area.y = self.mouse-y - self.pressed-y + work_area.y;
                root.view_pos_x = -(center_x + work_area.x - root.width / 2);
                root.view_pos_y = -(center_y + work_area.y - root.height / 2);
                root.moved_by(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
            }
            clicked => {
                if root.dragged == false {
                    root.workbench_clicked();
                }
            }
            double-clicked => {
                if root.dragged == false {
                    root.workbench_double_clicked();
                }
            }
            pointer-event(event) => {
                if event.button == PointerEventButton.left && event.kind == PointerEventKind.up {
                    root.dragged = false;
                }
                if event.kind == PointerEventKind.move {
                    // owo <- this comment was written without my explicit consent, I do not agree with those words
                    root.mouse_pos_x = self.mouse-x - center_x;
                    root.mouse_pos_y = self.mouse-y - center_y;
                }
            }
        }

        if debug_info:
        WorkAreaDebugLimit {
            line_color: root.background_detail_color;
        }
        @children
    }
}
