[package]
name = "tg-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
colored = { version = "3.0.0" }
directories = { version = "6.0.0" }

[dev-dependencies]
tempfile = { workspace = true }
pretty_assertions = { workspace = true }
