name: Release

# on:
#   push:
#     tags:
#       - "v*.*.*"

on:
  push:
    branches:
      - gh_action
env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Testenin
        run: echo "this is a test"
  #     - name: Create release --title "v0.1.0" --notes "Release v0.1.0"
  #       run: gh release create "v0.1.0" --draft
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    strategy:
      matrix:
        builds:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.builds.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Testenin
        run: echo ${{ matrix.builds.os }} ${{ matrix.builds.target }}

      # - name: Build
      #   run: cargo build --release --target ${{ matrix.builds.target }}

      # - name: Tests
      #   run: cargo test

      # - name: Package
      #   run: |
      #     export ARCHIVE_NAME="firework-0.1.0-${{ matrix.builds.target }}.zip"
      #     echo "::set-env name=ARCHIVE_NAME::$FOO"

      #     if [ '${{ matrix.builds.os }}' == 'windows-latest' ]; then
      #       export GUI_FILE="./target/release/rust-firework-gui-app.exe"
      #       export CLI_FILE="./target/release/rust-firework-cli-app.exe"
      #     else
      #       export GUI_FILE="./target/release/rust-firework-gui-app"
      #       export CLI_FILE="./target/release/rust-firework-cli-app"
      #     fi

      #     7z a -stl $ARCHIVE_NAME $GUI_FILE $CLI_FILE "License"
      #     7z rn $ARCHIVE_NAME GUI_FILE firework.exe
      #     7z rn $ARCHIVE_NAME CLI_FILE firework-cli.exe

      # - name: Upload
      #   run: |
      #     gh release upload v0.1.0 $ARCHIVE_NAME
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Testenin
        run: echo "this is a test"
  #     - name: Publish release
  #       run: |
  #         echo would run "gh release edit v0.1.0 --draft=false"
  #       env:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
